req_pkg:
  - dnsutils
  - sudo
  - adduser
  - curl
  - lsb-base
  - procps
  - zlib1g
  - gzip
  - sysstat
  - ntp
  - bash
  - tree
  - python
  - python-support
  - apt-transport-https
  - unzip
  - software-properties-common

packages:
  - java-1.8.0-openjdk-devel
  - python-httplib2
  - sysstat
  - lsof
  - parted
  - openssh-clients
  - unzip
  - curl
  - wget
  - iotop
  - ntpdate
  - chrony
  - nmap-ncat

update_grub: 'cd && grub2-mkconfig -o "$(readlink -n /etc/grub2.cfg)"'

ntp_service: chronyd
ntp_sync: "systemctl restart ntpdate"

epel_rpm_url: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epel_yum: "epel-release"

datastax_repo: "ubuntu-datastax_repo.j2"
datastax_repo_file: "/etc/apt/sources.list.d/datastax.sources.list"
datastax_repo_key: "http://debian.datastax.com/debian/repo_key"

